"""
Ouroboros AI - Database Models
SQLAlchemy models for PostgreSQL persistence
"""

from datetime import datetime, timezone
from sqlalchemy import (
    Column, Integer, String, Text, Float, DateTime, Boolean,
    ForeignKey, JSON, Enum as SQLEnum
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
import enum

Base = declarative_base()


def _utc_now() -> datetime:
    """Timezone-aware UTC now for SQLAlchemy column defaults."""
    return datetime.now(timezone.utc)


class ScanStatus(enum.Enum):
    """Scan status enumeration"""
    PENDING = "pending"
    SCANNING = "scanning"
    GENERATING_FIXES = "generating_fixes"
    VERIFYING = "verifying"
    CREATING_PR = "creating_pr"
    COMPLETED = "completed"
    FAILED = "failed"


class Scan(Base):
    """Scan record tracking complete workflow execution"""
    __tablename__ = "scans"
    
    id = Column(Integer, primary_key=True)
    scan_id = Column(String(100), unique=True, nullable=False, index=True)
    repo_url = Column(String(500), nullable=False)
    branch = Column(String(200), default="main")
    commit_sha = Column(String(40))
    
    status = Column(SQLEnum(ScanStatus), default=ScanStatus.PENDING)
    scan_profile = Column(String(50), default="standard")
    
    # Timestamps
    created_at = Column(DateTime, default=_utc_now)
    started_at = Column(DateTime)
    completed_at = Column(DateTime)
    
    # Results
    vulnerabilities_found = Column(Integer, default=0)
    fixes_generated = Column(Integer, default=0)
    fixes_verified = Column(Integer, default=0)
    
    # Outputs
    pr_url = Column(String(500))
    pr_number = Column(Integer)
    report_url = Column(String(500))
    
    # Metadata
    user_id = Column(String(100))
    error_message = Column(Text)
    scan_metadata = Column(JSON)
    
    # Relationships
    vulnerabilities = relationship("Vulnerability", back_populates="scan", cascade="all, delete-orphan")
    fixes = relationship("Fix", back_populates="scan", cascade="all, delete-orphan")
    audit_events = relationship("AuditEvent", back_populates="scan", cascade="all, delete-orphan")
    logs = relationship("ScanLog", back_populates="scan", cascade="all, delete-orphan")


class Vulnerability(Base):
    """Vulnerability discovered by RED agent"""
    __tablename__ = "vulnerabilities"
    
    id = Column(Integer, primary_key=True)
    vulnerability_id = Column(String(100), unique=True, nullable=False, index=True)
    scan_id = Column(Integer, ForeignKey("scans.id"), nullable=False)
    
    # Vulnerability details
    type = Column(String(200), nullable=False)
    severity = Column(String(50), nullable=False)  # critical|high|medium|low
    cwe = Column(String(50))
    cvss = Column(Float)
    
    # Location
    file_path = Column(Text, nullable=False)
    line_number = Column(Integer)
    function_name = Column(String(200))
    parameter = Column(String(200))
    
    # Description
    description = Column(Text, nullable=False)
    attack_vector = Column(String(50))  # network|local|adjacent|physical
    poc_code = Column(Text)
    poc_success_rate = Column(Float)
    remediation_hint = Column(Text)
    
    # Analysis
    tools_detected_by = Column(JSON)  # List of tools
    confidence = Column(Float)
    reasoning = Column(Text)
    
    # Governance
    risk_score = Column(Float)
    priority = Column(Integer)
    autonomy_level = Column(String(50))
    
    # Status
    fixed = Column(Boolean, default=False)
    verified = Column(Boolean, default=False)
    
    # Timestamps
    discovered_at = Column(DateTime, default=_utc_now)
    
    # Relationships
    scan = relationship("Scan", back_populates="vulnerabilities")
    fixes = relationship("Fix", back_populates="vulnerability")


class Fix(Base):
    """Fix generated by BLUE agent"""
    __tablename__ = "fixes"
    
    id = Column(Integer, primary_key=True)
    fix_id = Column(String(100), unique=True, nullable=False, index=True)
    scan_id = Column(Integer, ForeignKey("scans.id"), nullable=False)
    vulnerability_id = Column(Integer, ForeignKey("vulnerabilities.id"), nullable=False)
    
    # Fix details
    file_path = Column(Text, nullable=False)
    original_code = Column(Text, nullable=False)
    fixed_code = Column(Text, nullable=False)
    diff = Column(Text)
    
    # Reasoning
    chain_of_thought = Column(Text)
    rationale = Column(Text)
    confidence = Column(Float)
    
    # Safety gates
    passed_input_validation = Column(Boolean, default=False)
    passed_syntax_check = Column(Boolean, default=False)
    passed_backward_compat = Column(Boolean, default=False)
    passed_security_scan = Column(Boolean, default=False)
    passed_performance_check = Column(Boolean, default=False)
    
    # Verification
    verified = Column(Boolean, default=False)
    verification_attempts = Column(Integer, default=0)
    verification_result = Column(JSON)
    
    # Status
    applied = Column(Boolean, default=False)
    
    # Timestamps
    generated_at = Column(DateTime, default=_utc_now)
    verified_at = Column(DateTime)
    
    # Relationships
    scan = relationship("Scan", back_populates="fixes")
    vulnerability = relationship("Vulnerability", back_populates="fixes")


class AuditEvent(Base):
    """Immutable audit event (also logged to immudb)"""
    __tablename__ = "audit_events"
    
    id = Column(Integer, primary_key=True)
    event_id = Column(String(100), unique=True, nullable=False, index=True)
    scan_id = Column(Integer, ForeignKey("scans.id"), nullable=False)
    
    # Event details
    event_type = Column(String(100), nullable=False)
    entity_id = Column(String(100))  # RED-xxx, BLUE-xxx, etc.
    timestamp = Column(DateTime, default=_utc_now, nullable=False)
    
    # Event data
    details = Column(JSON)
    digital_signature = Column(String(100))
    
    # Compliance
    compliance_mappings = Column(JSON)
    
    # Relationships
    scan = relationship("Scan", back_populates="audit_events")


class ScanLog(Base):
    """Log entry persisted for a scan"""
    __tablename__ = "scan_logs"
    
    id = Column(Integer, primary_key=True)
    scan_id = Column(Integer, ForeignKey("scans.id"), nullable=False)
    
    # Log details
    timestamp = Column(DateTime, default=_utc_now)
    level = Column(String(20), default="INFO")
    source = Column(String(100), default="SYSTEM")
    message = Column(Text)
    
    # Relationships
    scan = relationship("Scan", back_populates="logs")


class User(Base):
    """User model for authentication"""
    __tablename__ = "users"
    
    id = Column(Integer, primary_key=True)
    user_id = Column(String(100), unique=True, nullable=False, index=True)
    email = Column(String(255), unique=True, nullable=False, index=True)
    hashed_password = Column(String(255), nullable=False)
    full_name = Column(String(255))
    is_active = Column(Boolean, default=True)
    
    # Timestamps
    created_at = Column(DateTime, default=_utc_now)
    updated_at = Column(DateTime, default=_utc_now, onupdate=_utc_now)

