#!/usr/bin/env python3
import io
import sys
from pathlib import Path
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseUpload, MediaIoBaseDownload

# Setup path to import settings
sys.path.append(str(Path(__file__).parent.parent))
from config.settings import settings

# ---------- CONFIG ----------
SERVICE_ACCOUNT_FILE = str(settings.google_service_account_file)
SHARED_FOLDER_ID = settings.google_docs_folder_id
REAL_USER_EMAIL = "" # Optional
LLM_TEXT = """# Ouroboros Security Report (Test)
This report was generated by the Documentation Agent to verify the robust .docx export workflow.
If you see this, the quota/permission workaround is successful.
"""

SCOPES = [
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/documents"
]

print(f"🚀 Starting Robust Doc Creation Script")
print(f"📂 Target Folder: {SHARED_FOLDER_ID}")

# ---------- BUILD CREDENTIALS ----------
creds = service_account.Credentials.from_service_account_file(
    SERVICE_ACCOUNT_FILE,
    scopes=SCOPES
)

print(f"🔑 Credential Scopes: {creds.scopes}")
print(f"📧 Service Account Email: {creds.service_account_email}")

docs_srv  = build('docs', 'v1', credentials=creds)
drive_srv = build('drive', 'v3', credentials=creds)

try:
    # ---------- 1️⃣ Create a native Google Docs file ----------
    print("1️⃣ Creating temporary Google Doc...")
    doc = docs_srv.documents().create(body={"title":"Ouroboros LLM Report (Temp)"}).execute()
    doc_id = doc["documentId"]
    print(f"✅ Created native Google Docs – id={doc_id}")

    # ---------- 2️⃣ Insert the LLM text ----------
    print("2️⃣ Inserting content...")
    insert_req = [{
        "insertText": {
            "location": {"index": 1},
            "text": LLM_TEXT
        }
    }]
    docs_srv.documents().batchUpdate(
        documentId=doc_id,
        body={"requests": insert_req}
    ).execute()
    print("✅ Inserted LLM text.")

    # ---------- 3️⃣ Export as .docx (in memory) ----------
    print("3️⃣ Exporting to .docx...")
    export_req = drive_srv.files().export_media(
        fileId=doc_id,
        mimeType='application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    )
    fh = io.BytesIO()
    downloader = MediaIoBaseDownload(fh, export_req)
    while not downloader.next_chunk()[1]:
        pass
    docx_bytes = fh.getvalue()
    print("✅ Exported .docx (binary in memory).")

    # ---------- 4️⃣ Upload .docx **into the shared folder** ----------
    print(f"4️⃣ Uploading to Shared Folder {SHARED_FOLDER_ID}...")
    metadata = {
        "name": "Ouroboros_Security_Report.docx",
        "mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "parents": [SHARED_FOLDER_ID]      # <--- forces placement in the shared folder
    }
    media = MediaIoBaseUpload(
        io.BytesIO(docx_bytes),
        mimetype='application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        resumable=True
    )
    uploaded = drive_srv.files().create(
        body=metadata,
        media_body=media,
        fields='id, name, webViewLink'
    ).execute()
    print(f"✅ Uploaded .docx to shared folder → fileId={uploaded['id']}")
    print(f"🔗 Link: {uploaded.get('webViewLink')}")

    # ---------- 5️⃣ Clean up the temporary native Docs file ----------
    print("5️⃣ Cleaning up temp file...")
    drive_srv.files().delete(fileId=doc_id).execute()
    print("✅ Temporary native Google Docs file deleted.")

except Exception as e:
    print(f"❌ Operation Failed: {e}")
    if 'doc_id' in locals():
        print("⚠️ Attempting cleanup of temp file...")
        try:
             drive_srv.files().delete(fileId=doc_id).execute()
        except:
            pass
