#!/usr/bin/env python3
import asyncio
import json
import logging
from datetime import datetime
from pathlib import Path
import sys
import os

# Setup path to import from src
sys.path.append(str(Path(__file__).parent.parent))

from src.agents.red_agent import REDAgent
from src.agents.governance_agent import GovernanceAgent
from src.agents.blue_agent import BLUEAgent
from src.integrations.github_api import GitHubClient
from config.settings import settings

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

async def run_full_cycle():
    logger.info("🚀 Starting Full Cycle Test (Red -> Governance -> Blue -> PR)")
    
    # Target
    target_repo = "https://github.com/samoylenko/vulnerable-app-nodejs-express.git"
    
    # 1. RED AGENT
    logger.info(f"🔴 [Phase 1] Running Red Agent Scan against {target_repo}")
    red_agent = REDAgent()
    red_result = await red_agent.execute({
        "repo_url": target_repo,
        "scan_profile": "standard"
    })
    
    vulnerabilities = red_result.get("vulnerabilities", [])
    logger.info(f"✅ Red Agent found {len(vulnerabilities)} vulnerabilities")
    
    if not vulnerabilities:
        logger.error("No vulnerabilities found! Aborting test.")
        return

    # 2. GOVERNANCE AGENT
    logger.info("⚖️ [Phase 2] Running Governance Agent")
    gov_agent = GovernanceAgent()
    gov_result = await gov_agent.execute({
        "vulnerabilities": vulnerabilities,
        "environment": "production"
    })
    
    prioritized_queue = gov_result.get("prioritized_queue", [])
    logger.info(f"✅ Governance prioritized {len(prioritized_queue)} items")
    
    # 3. BLUE AGENT
    logger.info("🔵 [Phase 3] Running Blue Agent (Fix Generation)")
    blue_agent = BLUEAgent()
    
    # Take the top priority item
    top_vuln = prioritized_queue[0]
    logger.info(f"Attempting to fix top vulnerability: {top_vuln.get('id')} ({top_vuln.get('type')})")
    
    # Extract code snippet if missing (Blue Agent expects 'vulnerable_code')
    # In a full run, we'd read it from the file. For now, use description or placeholder
    vuln_code = top_vuln.get("vulnerable_code")
    if not vuln_code:
        # Fallback: Read file from Red Agent sandbox if path available, else placeholder
        vuln_code = "# Vulnerable code placeholder (file read not implemented in this script version)"
    
    # Infer language
    file_path = top_vuln.get("location", {}).get("file", "")
    language = "python" # Default
    if file_path.endswith(".java"): language = "java"
    elif file_path.endswith(".js"): language = "javascript"
    elif file_path.endswith(".ts"): language = "typescript"
    elif file_path.endswith(".go"): language = "go"
    elif file_path.endswith(".php"): language = "php"
        
    blue_input = {
        "vulnerability_id": top_vuln.get("id"),
        "vulnerability_type": top_vuln.get("type"),
        "vulnerability_location": top_vuln.get("location", {}),
        "vulnerable_code": vuln_code,
        "cwe": top_vuln.get("cwe", "CWE-Unknown"),
        "cvss": top_vuln.get("cvss", 5.0),
        "language": language
    }
    
    blue_result = await blue_agent.execute(blue_input)
    
    fixes = blue_result.get("fixes", [])
    if not fixes:
        logger.warning("No fixes generated by Blue Agent. Creating dummy fix for PR test.")
        selected_fix = {
            "description": "Dummy Fix (Blue Agent failed)",
            "code_diff": {
                "file": top_vuln.get("location", {}).get("file", "unknown_file.py"),
                "before": "# Bad code",
                "after": "# Fixed code\n# Applied via Ouroboros CI",
                "lines_changed": 1
            }
        }
    else:
        # Use simple selection logic if not already selected
        selected_idx = blue_result.get("selected_fix", 1) - 1
        if 0 <= selected_idx < len(fixes):
            selected_fix = fixes[selected_idx]
        else:
            selected_fix = fixes[0]
            
    logger.info(f"✅ Selected Fix: {selected_fix.get('description')}")

    # 4. GITHUB PR (Integration)
    logger.info("🐙 [Phase 4] Creating Pull Request")
    
    client = GitHubClient()
    if not client.client:
        logger.error("GitHub client not initialized. Skipping PR creation.")
        return

    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    target_repo_name = target_repo.replace("https://github.com/", "").replace(".git", "")
    branch_name = f"fix-{top_vuln.get('id').lower().replace(' ', '-')}-{timestamp}"
    
    try:
        # Fork & Clone workflow (reusing logic from create_test_pr.py)
        logger.info(f"Forking {target_repo_name}...")
        fork_url = client.fork_repository(target_repo_name)
        
        # Clone Fork
        target_dir = Path("/tmp") / f"ouroboros_fix_{timestamp}"
        clean_url = fork_url.replace("https://", "")
        auth_url = f"https://{settings.github_token}@{clean_url}"
        
        # Helper to run git
        def run_git(args, cwd=None):
            subprocess.run(["git"] + args, cwd=str(cwd) if cwd else None, check=True)

        import subprocess
        logger.info(f"Cloning fork to {target_dir}")
        run_git(["clone", auth_url, str(target_dir)])
        
        # Checkout Branch
        logger.info(f"Creating branch {branch_name}")
        run_git(["-C", str(target_dir), "checkout", "-b", branch_name])
        
        # Apply Fix
        # For this test, we create/overwrite the file specified in location
        file_to_fix = selected_fix.get('code_diff', {}).get('file')
        if not file_to_fix or file_to_fix == "unknown":
            file_to_fix = "SECURITY_FIX.md" # Fallback
            
        fix_path = target_dir / file_to_fix
        fix_path.parent.mkdir(parents=True, exist_ok=True)
        
        logger.info(f"Applying fix to {file_to_fix}")
        
        # Helper: Normalize whitespace for fuzzy matching
        def normalize_ws(s):
            import re
            return re.sub(r'\s+', ' ', s.strip())
        
        if fix_path.exists():
            original_content = fix_path.read_text()
            before_code = selected_fix.get('code_diff', {}).get('before', '').strip()
            after_code = selected_fix.get('code_diff', {}).get('after', '').strip()
            
            # Smart Replacement Logic with whitespace normalization fallback
            if before_code and before_code in original_content:
                logger.info("Applying patch via exact search & replace...")
                new_content = original_content.replace(before_code, after_code)
                fix_path.write_text(new_content)
            elif before_code and normalize_ws(before_code) in normalize_ws(original_content):
                logger.info("Applying patch via normalized whitespace matching...")
                # Find where in the original content the normalized match occurs
                # For simplicity, still replace the first occurrence after finding
                new_content = original_content.replace(before_code.strip(), after_code)
                fix_path.write_text(new_content)
            else:
                logger.warning("Could not find 'before' code block. Appending fix to file (Manual resolution needed).")
                with open(fix_path, "a") as f:
                     f.write(f"\n\n# Ouroboros Security Fix:\n{after_code}")
        else:
            logger.info("File does not exist, creating new...")
            with open(fix_path, "w") as f:
                f.write(f"# Security Fix for {top_vuln.get('id')}\n")
                f.write(selected_fix.get('code_diff', {}).get('after', '# No code content'))
            
        # Commit & Push
        logger.info("Committing and pushing...")
        run_git(["-C", str(target_dir), "add", str(file_to_fix)])
        run_git(["-C", str(target_dir), "commit", "-m", f"fix: Resolve {top_vuln.get('id')}"])
        run_git(["-C", str(target_dir), "push", "-u", "origin", branch_name])
        
        # Create PR
        logger.info("Opening PR...")
        user = client.client.get_user().login
        head_ref = f"{user}:{branch_name}"
        
        # Get the default branch dynamically from the target repo
        target_repo_obj = client.client.get_repo(target_repo_name)
        default_branch = target_repo_obj.default_branch
        logger.info(f"Target repo default branch: {default_branch}")
        
        pr = client.create_pull_request(
            repo_full_name=target_repo_name,
            title=f"Security Fix: {top_vuln.get('id')}",
            body=f"Automated fix generated by Ouroboros AI.\n\n**Vulnerability:** {top_vuln.get('type')}\n**Severity:** {top_vuln.get('severity')}\n**Fix Approach:** {selected_fix.get('description')}",
            head_branch=head_ref,
            base_branch=default_branch
        )
        
        logger.info(f"🎉 SUCCESS! Full Cycle Complete. PR: {pr['pr_url']}")
        
    except Exception as e:
        logger.error(f"PR Creation failed: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    asyncio.run(run_full_cycle())
