"""
Ouroboros AI - BLUE Agent
Secure fix generation using DeepSeek-R1-Distill-Qwen-7B with chain-of-thought reasoning
"""

import logging
import json
import re
from typing import Dict, Any, List, Optional
from datetime import datetime
from pathlib import Path
from pydantic import BaseModel, Field
from langchain_community.llms import LlamaCpp

from src.agents.base_agent import BaseAgent, AgentInput, AgentOutput
from src.models import get_model
from src.security import safety_gates, GateResult

logger = logging.getLogger(__name__)


class CodeDiff(BaseModel):
    """Code diff for a fix"""
    file: str
    before: str
    after: str
    lines_changed: int


class FixOption(BaseModel):
    """Single fix option generated by BLUE Agent"""
    option: int
    description: str
    approach: str
    code_diff: CodeDiff
    test_code: str
    safety_gates: Dict[str, GateResult]
    confidence: float
    recommendation: str  # STRONG_ACCEPT|ACCEPT|WEAK_ACCEPT|REJECT
    reasoning: str = ""


class BLUEAgentInput(AgentInput):
    """Input schema for BLUE Agent"""
    vulnerability_id: str
    vulnerability_type: str
    vulnerability_location: Dict[str, Any]
    vulnerable_code: str
    cwe: str
    cvss: float
    language: str = Field(default="python")
    sandbox_path: Optional[str] = Field(default=None)  # Path to cloned repo for file reading


class BLUEAgentOutput(AgentOutput):
    """Output schema for BLUE Agent"""
    fix_id: str
    vulnerability_id: str
    fixes: List[FixOption]
    selected_fix: int
    statistics: Dict[str, Any]


class BLUEAgent(BaseAgent):
    """
    BLUE Agent - Defensive security specialist
    
    Uses DeepSeek-R1-Distill-Qwen-7B for secure fix generation
    with systematic debugging methodology from obra/superpowers
    """
    
    def __init__(self):
        """Initialize BLUE Agent with DeepSeek-R1 model"""
        model = get_model("blue")
        super().__init__(model=model, agent_id="BLUE")
        
        # Comprehensive System Prompt - Handles all vulnerability types
        self.system_prompt = """You are a security expert who fixes vulnerabilities in code.

## YOUR EXPERTISE
- Secure coding in Python, JavaScript, Java, Go, PHP, Rust
- Container security (Docker, Kubernetes)
- Infrastructure as Code security (Terraform, CloudFormation)
- OWASP Top 10 and CWE vulnerability patterns
- Defense-in-depth security principles

## FIX PRINCIPLES
1. Understand the ROOT CAUSE before fixing
2. Use safe APIs and parameterized queries
3. Validate input, encode output
4. Make minimal, surgical changes
5. Preserve existing functionality

## COMMON FIX PATTERNS BY CATEGORY

### Code Vulnerabilities
- SQL Injection: Use parameterized queries, never string concat
- XSS: Use html.escape(), textContent, or template auto-escaping
- Command Injection: Use subprocess with list args, no shell=True
- Path Traversal: Use os.path.basename() or validate against allowlist
- SSRF: Validate URLs against domain allowlist

### Container Security (Dockerfile)
- Root User (CWE-250): Add USER non-root instruction
  Example: USER node or USER 1000:1000
- Missing HEALTHCHECK (CWE-20): Add HEALTHCHECK instruction
  Example: HEALTHCHECK --interval=30s --timeout=3s CMD curl -f http://localhost/ || exit 1
- Unpinned Base Image: Use specific version tags
  Example: FROM node:18.19.0-alpine instead of FROM node:latest
- Secrets in ENV: Use build args or secrets management
  Example: Use --mount=type=secret instead of ENV

### Configuration Security
- Debug Mode: Ensure DEBUG=False in production
- CORS Misconfiguration: Restrict Access-Control-Allow-Origin
- Missing Security Headers: Add CSP, X-Frame-Options, etc.
- Insecure TLS: Enforce TLS 1.2+ with strong ciphers"""
        
        # Fix templates by vulnerability type (fallback when LLM fails)
        # Extended with patterns from blue_agent_system_prompt.md
        self.fix_templates = {
            "sql_injection": {
                "approach": "parameterized_query",
                "pattern_before": r"execute\s*\(.*?\+.*?\)",
                "fix_hint": "Use parameterized queries with placeholders"
            },
            "xss": {
                "approach": "html_escaping",
                "pattern_before": r"innerHTML|document\.write|\$\{.*?\}",
                "fix_hint": "Use html.escape() or textContent with CSP headers"
            },
            "command_injection": {
                "approach": "safe_subprocess",
                "pattern_before": r"shell\s*=\s*True|os\.system",
                "fix_hint": "Use subprocess with list arguments, no shell=True"
            },
            "path_traversal": {
                "approach": "path_validation",
                "pattern_before": r"\.\./|\.\.\\\\|\.\.",
                "fix_hint": "Use os.path.basename or pathlib to sanitize"
            },
            "ssrf": {
                "approach": "url_allowlist",
                "pattern_before": r"requests\.get\(.*user|urllib.*user|fetch\(.*user",
                "fix_hint": "Validate URLs against allowlist, block private IPs"
            },
            "insecure_deserialization": {
                "approach": "safe_serialization",
                "pattern_before": r"pickle\.loads|yaml\.load\(|unserialize\(",
                "fix_hint": "Use JSON instead of pickle, or add HMAC verification"
            },
            "idor": {
                "approach": "authorization_check",
                "pattern_before": r"\.get\(.*id|params\[.id|req\.params\.id",
                "fix_hint": "Add authorization check: verify user owns the resource"
            },
            "authentication_bypass": {
                "approach": "secure_auth",
                "pattern_before": r"password\s*==|md5\(|sha1\(",
                "fix_hint": "Use bcrypt/argon2, implement proper session management"
            },
            "cryptographic_failure": {
                "approach": "modern_crypto",
                "pattern_before": r"DES|MD5|SHA1|ECB|random\(",
                "fix_hint": "Use AES-256-GCM, secrets module for random"
            },
            "security_misconfiguration": {
                "approach": "secure_config",
                "pattern_before": r"debug\s*=\s*True|CORS\(\*\)|Access-Control-Allow-Origin:\s*\*",
                "fix_hint": "Disable debug mode, restrict CORS, add security headers"
            },
            # Dockerfile-specific vulnerabilities
            "configuration_misconfiguration": {
                "approach": "container_hardening",
                "pattern_before": r"FROM.*:latest|^(?!.*USER)",
                "fix_hint": "Add USER instruction for non-root, add HEALTHCHECK, pin base image versions"
            },
            "cwe-250": {  # Execution with Unnecessary Privileges
                "approach": "least_privilege",
                "pattern_before": r"FROM|WORKDIR",
                "fix_hint": "Add 'USER node' or 'USER 1000:1000' before CMD/ENTRYPOINT"
            },
            "cwe-20": {  # Improper Input Validation
                "approach": "health_monitoring",
                "pattern_before": r"CMD|ENTRYPOINT",
                "fix_hint": "Add HEALTHCHECK instruction for container health monitoring"
            },
            "root_user": {
                "approach": "non_root_user",
                "pattern_before": r"FROM",
                "fix_hint": "Add USER instruction: USER node or USER 1000:1000"
            },
            "missing_healthcheck": {
                "approach": "add_healthcheck",
                "pattern_before": r"CMD|ENTRYPOINT",
                "fix_hint": "Add HEALTHCHECK --interval=30s --timeout=3s CMD curl -f http://localhost/ || exit 1"
            }
        }
    
    def validate_input(self, input_data: Dict[str, Any]) -> BLUEAgentInput:
        """Validate BLUE Agent input"""
        return BLUEAgentInput(**input_data)
    
    async def execute(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute BLUE Agent fix generation
        
        Steps:
        1. Analyze vulnerability with DeepSeek-R1
        2. Generate 3 fix options
        3. Validate each fix through 5 safety gates
        4. Select best fix (highest confidence + all gates passed)
        """
        fix_id = f"BLUE-{datetime.now().strftime('%Y%m%d-%H%M%S')}-{input_data['vulnerability_id']}"
        self.logger.info(f"Generating fix {fix_id} for {input_data['vulnerability_type']}")
        
        try:
            # Step 1: Generate fix options with DeepSeek-R1
            self.logger.info("Generating fix options with DeepSeek-R1...")
            fix_options = await self._generate_fixes(input_data)
            
            # Step 2: Validate each fix through safety gates
            self.logger.info("Validating fixes through safety gates...")
            validated_fixes = []
            for fix_option in fix_options:
                validated_fix = await self._validate_fix(fix_option, input_data)
                validated_fixes.append(validated_fix)
            
            # Step 3: Select best fix
            selected_fix_idx = self._select_best_fix(validated_fixes)
            
            self.logger.info(f"Selected fix option {selected_fix_idx + 1}")
            
            # Calculate statistics
            statistics = {
                "total_options": len(validated_fixes),
                "avg_confidence": sum(f.confidence for f in validated_fixes) / len(validated_fixes),
                "all_gates_passed": all(
                    all(g.status.value == "passed" for g in f.safety_gates.values())
                    for f in validated_fixes
                )
            }
            
            return {
                "fix_id": fix_id,
                "vulnerability_id": input_data["vulnerability_id"],
                "fixes": [f.model_dump() for f in validated_fixes],
                "selected_fix": selected_fix_idx + 1,
                "statistics": statistics
            }
            
        except Exception as e:
            self.logger.error(f"BLUE Agent execution failed: {e}", exc_info=True)
            return {
                "fix_id": fix_id,
                "vulnerability_id": input_data["vulnerability_id"],
                "fixes": [],
                "selected_fix": 0,
                "statistics": {"error": str(e)}
            }
    
    def _sanitize_file_path(self, file_path: str, sandbox_path: str = "") -> str:
        """
        Clean up file paths that may have:
        - Absolute /tmp/... prefixes from sandbox
        - Fake /app/... prefixes from LLM hallucination
        - Placeholder paths like /path/to/file
        - Leading slashes
        """
        if not file_path:
            return ""
        
        # Remove common LLM hallucination prefixes (order matters - check longer first)
        prefixes_to_strip = [
            "/path/to/", "path/to/",      # Common LLM placeholder
            "/actual/", "actual/",         # Another common placeholder
            "/app/", "/src/", "/code/", "/project/",
            "app/", "src/", "code/", "project/"
        ]
        
        # Remove sandbox path prefix if present
        if sandbox_path and file_path.startswith(sandbox_path):
            file_path = file_path[len(sandbox_path):].lstrip("/")
        
        # Strip /tmp/ouroboros... prefixes
        if "/tmp/ouroboros" in file_path:
            parts = file_path.split("/tmp/ouroboros")
            if len(parts) > 1:
                remaining = parts[-1]
                # Remove the timestamp directory
                if "/" in remaining:
                    remaining = "/".join(remaining.split("/")[2:])
                file_path = remaining
        
        # Strip common prefixes (try each one)
        for prefix in prefixes_to_strip:
            if file_path.startswith(prefix):
                file_path = file_path[len(prefix):]
                break
        
    def _get_cwe_fix_guidance(self, cwe: str, vuln_type: str, language: str) -> str:
        """
        Get specific fix guidance based on CWE and vulnerability type.
        This helps the LLM generate the correct fix.
        """
        cwe_upper = cwe.upper() if cwe else ""
        vuln_lower = vuln_type.lower() if vuln_type else ""
        
        # Dockerfile-specific guidance
        if language == "dockerfile":
            if "250" in cwe_upper or "root" in vuln_lower or "privilege" in vuln_lower:
                return """For CWE-250 (Execution with Unnecessary Privileges):
- Add a USER instruction to run as non-root
- Example: Add 'USER node' or 'USER 1000:1000' BEFORE the CMD/ENTRYPOINT
- The fixed Dockerfile MUST include a USER instruction"""
            
            if "20" in cwe_upper or "healthcheck" in vuln_lower or "input" in vuln_lower:
                return """For CWE-20 (Improper Input Validation) / Missing HEALTHCHECK:
- Add a HEALTHCHECK instruction for container health monitoring
- Example: HEALTHCHECK --interval=30s --timeout=3s CMD curl -f http://localhost:3000/ || exit 1
- The fixed Dockerfile MUST include a HEALTHCHECK instruction"""
            
            # Generic Dockerfile fix
            return """For Dockerfile security:
- Add USER instruction for non-root execution (e.g., USER node)
- Add HEALTHCHECK instruction for health monitoring
- Pin base image versions (avoid :latest)
- The fixed code MUST include both USER and HEALTHCHECK if missing"""
        
        # Code vulnerability guidance
        cwe_guidance = {
            "89": "Use parameterized queries or prepared statements. Never concatenate user input into SQL.",
            "79": "Escape HTML output using html.escape() or use template auto-escaping. Set CSP headers.",
            "78": "Use subprocess with list arguments, never shell=True. Validate and sanitize all inputs.",
            "22": "Use os.path.basename() or validate paths against an allowlist. Block '..' sequences.",
            "918": "Validate URLs against a domain allowlist. Block private IP ranges (10.x, 192.168.x, 127.x).",
            "502": "Avoid pickle/yaml.load. Use JSON or add HMAC signature verification.",
            "639": "Add authorization checks to verify the user owns the requested resource.",
            "287": "Use bcrypt/argon2 for password hashing. Implement secure session management.",
            "327": "Use AES-256-GCM for encryption. Use secrets module for random number generation.",
        }
        
        # Extract CWE number
        import re
        cwe_match = re.search(r'(\d+)', cwe_upper)
        if cwe_match:
            cwe_num = cwe_match.group(1)
            if cwe_num in cwe_guidance:
                return f"For {cwe}: {cwe_guidance[cwe_num]}"
        
        # Fallback based on vulnerability type
        vuln_guidance = {
            "sql": "Use parameterized queries with placeholders (?)",
            "xss": "Use html.escape() or textContent instead of innerHTML",
            "command": "Use subprocess with list args, no shell=True",
            "path": "Use os.path.basename() to sanitize file paths",
            "ssrf": "Validate URLs against an allowlist",
            "config": "Disable debug mode, restrict CORS, add security headers",
        }
        
        for key, guidance in vuln_guidance.items():
            if key in vuln_lower:
                return guidance
        
        return "Fix the security vulnerability while preserving functionality."
        return file_path.lstrip("/")
    
    def _read_file_content(self, sandbox_path: str, file_path: str) -> Optional[str]:
        """
        Read actual file content from sandbox for accurate fix generation.
        """
        if not sandbox_path or not file_path:
            return None
            
        try:
            full_path = Path(sandbox_path) / file_path
            if full_path.exists() and full_path.is_file():
                content = full_path.read_text(errors='ignore')
                # Limit to 4000 chars to fit in context
                if len(content) > 4000:
                    content = content[:4000] + "\n... (truncated)"
                self.logger.info(f"Read {len(content)} chars from {file_path}")
                return content
        except Exception as e:
            self.logger.warning(f"Failed to read file {file_path}: {e}")
        return None
    
    async def _generate_fixes(self, vuln_data: Dict[str, Any]) -> List[FixOption]:
        """
        Generate fix options using DeepSeek-R1 with systematic debugging methodology.
        
        The model is prompted to:
        1. Trace the root cause (not just see the symptom)
        2. Analyze the data flow
        3. Fix at source with defense-in-depth
        4. Generate tests to verify the fix
        """
        # Try to read actual file content if sandbox path provided
        sandbox_path = vuln_data.get('sandbox_path')
        file_path = vuln_data.get('vulnerability_location', {}).get('file', '')
        
        actual_code = self._read_file_content(sandbox_path, file_path)
        if actual_code:
            vuln_data['vulnerable_code'] = actual_code
            self.logger.info(f"Using actual file content from {file_path}")
        
        vuln_type = vuln_data['vulnerability_type']
        vuln_code = vuln_data['vulnerable_code'][:3000]  # Generous context for root cause analysis
        cwe = vuln_data.get('cwe', 'Unknown')
        location = vuln_data.get('vulnerability_location', {})
        line_number = location.get('line', 'unknown')
        language = vuln_data.get('language', 'python').lower()
        
        # Get CWE-specific fix guidance
        fix_guidance = self._get_cwe_fix_guidance(cwe, vuln_type, language)
        
        # Construct simple Markdown-based prompt (no complex JSON required)
        prompt = f"""You are a security expert. Fix this vulnerability.

## VULNERABILITY
- Type: {vuln_type}
- CWE: {cwe}  
- File: {file_path}
- Line: {line_number}
- Language: {language}

## CURRENT CODE
```
{vuln_code}
```

## REQUIRED FIX
{fix_guidance}

## YOUR TASK
Provide the FIXED code that removes this vulnerability.

Respond in this EXACT format:

### ROOT CAUSE
Brief explanation of why this code is vulnerable.

### VULNERABLE CODE
```
<paste the exact vulnerable lines that need to be replaced>
```

### FIXED CODE  
```
<your secure replacement code - complete and working>
```

### EXPLANATION
What your fix does to prevent the vulnerability.

IMPORTANT:
- The VULNERABLE CODE must match EXACTLY what's in the file
- The FIXED CODE must be complete and working (not pseudocode)
- Keep changes minimal - only fix the security issue
- MUST include the required fix from above"""
        
        # Try up to 2 times
        for attempt in range(2):
            try:
                response = self._call_llm(prompt)
                
                # Parse Markdown response (much simpler than JSON!)
                fix_data = self._parse_markdown_response(response, file_path, vuln_code, vuln_type)
                
                if fix_data:
                    self.logger.info(f"Root cause: {fix_data.get('reasoning', 'N/A')[:100]}")
                    
                    # Create FixOption
                    # Generate valid Python test function name (sanitize spaces and special chars)
                    safe_vuln_name = re.sub(r'[^a-zA-Z0-9]', '_', vuln_type).lower().strip('_')
                    fix = FixOption(
                        option=1,
                        description=fix_data.get("description", f"Fix {vuln_type}"),
                        approach="defense_in_depth",
                        code_diff=CodeDiff(
                            file=fix_data.get("file", file_path),
                            before=fix_data.get("before", ""),
                            after=fix_data.get("after", ""),
                            lines_changed=len(fix_data.get("after", "").split("\n"))
                        ),
                        test_code=f"def test_{safe_vuln_name}_fix():\n    # Test that vulnerability is fixed\n    assert True  # Placeholder - actual tests depend on vulnerability type\n",
                        safety_gates={},
                        confidence=0.8,
                        recommendation="PENDING",
                        reasoning=fix_data.get("reasoning", "")
                    )
                    
                    self.logger.info(f"Generated fix using Markdown parsing")
                    return [fix]
                    
            except Exception as e:
                self.logger.warning(f"Attempt {attempt + 1} failed: {e}")
                if attempt == 0:
                    # Retry with even simpler prompt
                    prompt = f"""Fix this {vuln_type} vulnerability in {file_path}:

```
{vuln_code[:1000]}
```

Show the VULNERABLE CODE and FIXED CODE in separate code blocks."""
                    continue
        
        # All attempts failed - use template fallback
        self.logger.warning("Markdown parsing failed, using template-based fix")
        return [self._create_template_fix(vuln_data)]
    
    def _parse_markdown_response(self, response: str, file_path: str, vuln_code: str, vuln_type: str) -> Optional[Dict[str, Any]]:
        """
        Parse Markdown response to extract fix information.
        Much simpler and more reliable than JSON parsing!
        
        Expected format:
        ### ROOT CAUSE
        <explanation>
        
        ### VULNERABLE CODE
        ```
        <code>
        ```
        
        ### FIXED CODE
        ```
        <code>
        ```
        """
        import re
        
        result = {
            "file": file_path,
            "before": "",
            "after": "",
            "description": f"Fix {vuln_type}",
            "reasoning": ""
        }
        
        # Extract ROOT CAUSE / EXPLANATION section
        root_cause_match = re.search(
            r'(?:###?\s*(?:ROOT\s*CAUSE|EXPLANATION|WHY|ANALYSIS)[^\n]*\n)(.*?)(?=###|\Z)',
            response, re.IGNORECASE | re.DOTALL
        )
        if root_cause_match:
            result["reasoning"] = root_cause_match.group(1).strip()[:500]
        
        # Extract code blocks - find all ``` blocks
        code_blocks = re.findall(r'```(?:\w+)?\n(.*?)```', response, re.DOTALL)
        
        if len(code_blocks) >= 2:
            # First code block after "VULNERABLE" = before code
            # First code block after "FIXED" = after code
            
            # Try to find labeled sections
            vuln_section = re.search(
                r'(?:###?\s*(?:VULNERABLE|ORIGINAL|BEFORE|CURRENT)[^\n]*\n.*?```(?:\w+)?\n)(.*?)```',
                response, re.IGNORECASE | re.DOTALL
            )
            fixed_section = re.search(
                r'(?:###?\s*(?:FIXED|SECURE|AFTER|NEW|PATCHED)[^\n]*\n.*?```(?:\w+)?\n)(.*?)```',
                response, re.IGNORECASE | re.DOTALL
            )
            
            if vuln_section and fixed_section:
                result["before"] = vuln_section.group(1).strip()
                result["after"] = fixed_section.group(1).strip()
            else:
                # Fallback: first block = before, second = after
                result["before"] = code_blocks[0].strip()
                result["after"] = code_blocks[1].strip()
                
        elif len(code_blocks) == 1:
            # Only one code block - assume it's the fix
            result["after"] = code_blocks[0].strip()
            # Use snippet of vulnerable code as "before"
            result["before"] = vuln_code[:200].strip()
            
        else:
            # No code blocks found - try to extract inline code
            self.logger.warning("No code blocks found in response")
            return None
        
        # Extract description if present
        desc_match = re.search(
            r'(?:###?\s*(?:EXPLANATION|DESCRIPTION|WHAT|FIX)[^\n]*\n)(.*?)(?=###|\Z)',
            response, re.IGNORECASE | re.DOTALL
        )
        if desc_match:
            result["description"] = desc_match.group(1).strip()[:200]
        
        # Validate we have actual fix code
        if not result["after"] or len(result["after"]) < 5:
            self.logger.warning("No valid fix code extracted")
            return None
            
        return result

    async def _validate_fix(self, fix: FixOption, vuln_data: Dict[str, Any]) -> FixOption:
        """
        Validate a fix through 5 safety gates
        """
        self.logger.info(f"Validating fix option {fix.option}")
        
        # Run safety gates
        all_passed, gate_results = await safety_gates.validate_fix(
            original_code=vuln_data["vulnerable_code"],
            fixed_code=fix.code_diff.after,
            test_code=fix.test_code,
            language=vuln_data.get("language", "python")
        )
        
        # Convert gate results to dict
        fix.safety_gates = {
            gate.gate_name: gate
            for gate in gate_results
        }
        
        # Adjust confidence based on gate results
        if not all_passed:
            fix.confidence = min(fix.confidence, 0.5)
            fix.recommendation = "REJECT"
        elif fix.confidence >= 0.9:
            fix.recommendation = "STRONG_ACCEPT"
        elif fix.confidence >= 0.8:
            fix.recommendation = "ACCEPT"
        else:
            fix.recommendation = "WEAK_ACCEPT"
        
        return fix
    
    def _select_best_fix(self, fixes: List[FixOption]) -> int:
        """
        Select the best fix from multiple options
        
        Priority:
        1. All safety gates passed
        2. Highest confidence score
        3. Simplest approach (lowest lines changed)
        """
        # Filter for fixes with all gates passed
        valid_fixes = [
            (i, f) for i, f in enumerate(fixes)
            if all(g.status.value == "passed" for g in f.safety_gates.values())
        ]
        
        if not valid_fixes:
            self.logger.warning("No fixes passed all safety gates, selecting best available")
            valid_fixes = list(enumerate(fixes))
        
        # Sort by confidence (descending)
        valid_fixes.sort(key=lambda x: x[1].confidence, reverse=True)
        
        return valid_fixes[0][0]
    
    def _create_template_fix(self, vuln_data: Dict[str, Any]) -> FixOption:
        """
        Create an intelligent template-based fix using systematic debugging principles.
        
        Even as a fallback, we apply:
        1. Root cause identification (template-based)
        2. Defense-in-depth (multiple layers)
        3. Language-appropriate patterns
        """
        vuln_type = vuln_data.get("vulnerability_type", "unknown").lower()
        file_path = vuln_data.get("vulnerability_location", {}).get("file", "unknown")
        vuln_code = vuln_data.get("vulnerable_code", "")[:500]
        language = vuln_data.get("language", "python")
        
        # Get template for this vulnerability type
        template = self.fix_templates.get(vuln_type, {})
        approach = template.get("approach", "manual_review")
        hint = template.get("fix_hint", "Review and fix manually")
        
        # Defense-in-depth fixes by vulnerability type and language
        if vuln_type == "sql_injection":
            root_cause = "String interpolation/concatenation in SQL query allows attacker-controlled input"
            if language == "javascript":
                after_code = """// DEFENSE-IN-DEPTH FIX for SQL Injection
// Layer 1 (Entry): Validate input type and format
const userId = parseInt(req.params.id, 10);
if (isNaN(userId) || userId < 0) {
    return res.status(400).json({ error: 'Invalid user ID' });
}

// Layer 2 (Business): Use parameterized query
const result = await client.query(
    'SELECT * FROM users WHERE id = $1',
    [userId]
);

// Layer 3 (Output): Return only necessary fields
res.json({ id: result.rows[0]?.id, name: result.rows[0]?.name });"""
            elif language == "python":
                after_code = """# DEFENSE-IN-DEPTH FIX for SQL Injection
# Layer 1 (Entry): Validate input
user_id = request.args.get('id')
if not user_id or not user_id.isdigit():
    return jsonify({'error': 'Invalid user ID'}), 400

# Layer 2 (Business): Parameterized query
cursor.execute('SELECT * FROM users WHERE id = %s', (int(user_id),))

# Layer 3 (Detection): Log for monitoring
logger.info(f'User lookup: id={user_id}')"""
            else:
                after_code = f"// {hint}\n// Use parameterized queries with placeholders"
                
        elif vuln_type == "xss":
            root_cause = "User input rendered in HTML without context-aware encoding"
            if language == "javascript":
                after_code = """// DEFENSE-IN-DEPTH FIX for XSS
// Layer 1 (Entry): Validate/sanitize input
const name = req.query.name?.replace(/[<>&"']/g, '') || 'Guest';

// Layer 2 (Output): Use textContent, not innerHTML
// Or use a template engine with auto-escaping
res.render('hello', { name: encodeURIComponent(name) });

// Layer 3 (Headers): Set CSP header
res.setHeader('Content-Security-Policy', "default-src 'self'");"""
            else:
                after_code = """# DEFENSE-IN-DEPTH FIX for XSS
import html
# Layer 1: Validate input
# Layer 2: Encode output
safe_output = html.escape(user_input)
# Layer 3: Set CSP headers"""
                
        elif vuln_type == "command_injection":
            root_cause = "User input passed to shell execution without validation"
            after_code = """# DEFENSE-IN-DEPTH FIX for Command Injection
import subprocess
import shlex

# Layer 1 (Entry): Allowlist validation
ALLOWED_COMMANDS = {'ls', 'cat', 'grep'}
if command not in ALLOWED_COMMANDS:
    raise ValueError(f'Command not allowed: {command}')

# Layer 2 (Business): Use subprocess with list args, NO SHELL
result = subprocess.run(
    [command, *args],  # List, not string
    shell=False,       # NEVER shell=True with user input
    capture_output=True,
    timeout=30
)

# Layer 3 (Detection): Log command execution
logger.warning(f'Command executed: {command} by user {user_id}')"""
                
        elif vuln_type == "path_traversal":
            root_cause = "User-controlled path used without validation against directory escape"
            after_code = """# DEFENSE-IN-DEPTH FIX for Path Traversal
import os
from pathlib import Path

# Layer 1 (Entry): Strip dangerous sequences
filename = os.path.basename(user_input)  # Removes ../

# Layer 2 (Business): Validate within allowed directory
SAFE_DIR = Path('/app/uploads').resolve()
requested_path = (SAFE_DIR / filename).resolve()

if not str(requested_path).startswith(str(SAFE_DIR)):
    raise ValueError('Path traversal attempt detected')

# Layer 3 (Detection): Log access attempts
logger.info(f'File access: {requested_path} by {user_id}')"""

        elif vuln_type in ("ssrf", "server_side_request_forgery"):
            root_cause = "User-controlled URL passed to server-side HTTP request without validation"
            after_code = """# DEFENSE-IN-DEPTH FIX for SSRF
import ipaddress
from urllib.parse import urlparse

# Layer 1 (Entry): URL allowlist validation
ALLOWED_HOSTS = {'api.example.com', 'cdn.example.com'}
parsed = urlparse(user_url)

if parsed.hostname not in ALLOWED_HOSTS:
    raise ValueError(f'Host not allowed: {parsed.hostname}')

# Layer 2 (Business): Block private/internal IPs
try:
    ip = ipaddress.ip_address(parsed.hostname)
    if ip.is_private or ip.is_loopback or ip.is_link_local:
        raise ValueError('Internal IP addresses not allowed')
except ValueError:
    pass  # Hostname, not IP - already validated against allowlist

# Layer 3 (Request): Disable redirects, set timeout
response = requests.get(user_url, allow_redirects=False, timeout=10)

# Layer 4 (Detection): Log external requests
logger.warning(f'External request to {parsed.hostname} by user {user_id}')"""

        elif vuln_type in ("idor", "insecure_direct_object_reference"):
            root_cause = "Direct object reference without authorization check - user can access others' data"
            if language == "javascript":
                after_code = """// DEFENSE-IN-DEPTH FIX for IDOR
// Layer 1 (Entry): Validate input format
const resourceId = parseInt(req.params.id, 10);
if (isNaN(resourceId)) {
    return res.status(400).json({ error: 'Invalid resource ID' });
}

// Layer 2 (Authorization): Verify user owns or can access this resource
const resource = await Resource.findById(resourceId);
if (!resource) {
    return res.status(404).json({ error: 'Resource not found' });
}

if (resource.ownerId !== req.user.id && !req.user.isAdmin) {
    // Layer 3 (Detection): Log unauthorized access attempt
    logger.warn(`IDOR attempt: user ${req.user.id} tried to access resource ${resourceId}`);
    return res.status(403).json({ error: 'Access denied' });
}

res.json(resource);"""
            else:
                after_code = """# DEFENSE-IN-DEPTH FIX for IDOR
# Layer 1 (Entry): Validate input
resource_id = request.args.get('id')
if not resource_id or not resource_id.isdigit():
    return jsonify({'error': 'Invalid resource ID'}), 400

# Layer 2 (Authorization): Verify ownership
resource = Resource.query.get(int(resource_id))
if not resource:
    return jsonify({'error': 'Not found'}), 404

if resource.owner_id != current_user.id and not current_user.is_admin:
    # Layer 3 (Detection): Log unauthorized access
    logger.warning(f'IDOR attempt: user {current_user.id} -> resource {resource_id}')
    return jsonify({'error': 'Access denied'}), 403

return jsonify(resource.to_dict())"""

        elif vuln_type in ("insecure_deserialization", "deserialization"):
            root_cause = "Untrusted data deserialized without validation - allows code execution"
            after_code = """# DEFENSE-IN-DEPTH FIX for Insecure Deserialization
import json
import hmac
import hashlib

# Layer 1 (Prevention): Use safe format (JSON instead of pickle)
# NEVER: data = pickle.loads(user_input)
# INSTEAD:
data = json.loads(user_input)  # JSON cannot execute code

# Layer 2 (If pickle required): HMAC signature verification
SECRET_KEY = os.environ['SERIALIZATION_SECRET']
received_signature = request.headers.get('X-Data-Signature')
expected_signature = hmac.new(SECRET_KEY.encode(), user_input, hashlib.sha256).hexdigest()

if not hmac.compare_digest(received_signature, expected_signature):
    raise ValueError('Invalid data signature - tampering detected')

# Layer 3 (Allowlist): Only deserialize known classes
ALLOWED_CLASSES = {'User', 'Order', 'Product'}
if data.get('__class__') not in ALLOWED_CLASSES:
    raise ValueError(f'Class not allowed: {data.get("__class__")}')

# Layer 4 (Detection): Log deserialization events
logger.info(f'Deserialized {data.get("__class__")} by user {user_id}')"""

        elif vuln_type in ("authentication_bypass", "broken_authentication", "auth"):
            root_cause = "Weak authentication mechanism allows unauthorized access"
            after_code = """# DEFENSE-IN-DEPTH FIX for Authentication Bypass
import bcrypt
import secrets
from datetime import datetime, timedelta

# Layer 1 (Password): Use bcrypt, not MD5/SHA1
# NEVER: if md5(password) == stored_hash
# INSTEAD:
stored_hash = user.password_hash  # bcrypt hash from DB
if not bcrypt.checkpw(password.encode(), stored_hash):
    # Layer 2 (Rate Limiting): Track failed attempts
    failed_attempts.increment(username)
    if failed_attempts.get(username) > 5:
        logger.warning(f'Account lockout triggered for {username}')
        return jsonify({'error': 'Account locked. Try again later.'}), 429
    return jsonify({'error': 'Invalid credentials'}), 401

# Layer 3 (Session): Secure session token
session_token = secrets.token_urlsafe(32)
session.set_cookie('session', session_token, 
    httponly=True, secure=True, samesite='Strict',
    expires=datetime.now() + timedelta(hours=24))

# Layer 4 (Detection): Log successful auth
logger.info(f'User {username} authenticated from {request.remote_addr}')"""

        elif vuln_type in ("cryptographic_failure", "weak_crypto", "crypto"):
            root_cause = "Use of weak/deprecated cryptographic algorithms"
            after_code = """# DEFENSE-IN-DEPTH FIX for Cryptographic Failures
import secrets
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

# Layer 1 (Random): Use secrets, not random
# NEVER: token = ''.join(random.choices(string.ascii_letters, k=32))
# INSTEAD:
token = secrets.token_urlsafe(32)

# Layer 2 (Encryption): Use AES-256-GCM, not DES/3DES/ECB
key = secrets.token_bytes(32)  # 256-bit key
aesgcm = AESGCM(key)
nonce = secrets.token_bytes(12)
ciphertext = aesgcm.encrypt(nonce, plaintext.encode(), associated_data)

# Layer 3 (Hashing): Use SHA-256+, not MD5/SHA1
# NEVER: hashlib.md5(password).hexdigest()
# INSTEAD:
kdf = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=salt, iterations=600000)
key = kdf.derive(password.encode())

# Layer 4 (TLS): Enforce TLS 1.2+
# Configure in web server/load balancer"""

        elif vuln_type in ("security_misconfiguration", "misconfiguration"):
            root_cause = "Insecure default configuration exposes application to attacks"
            after_code = """# DEFENSE-IN-DEPTH FIX for Security Misconfiguration

# Layer 1 (Debug): Disable debug mode in production
# NEVER: app.run(debug=True) or DEBUG=True in settings
import os
DEBUG = os.environ.get('ENV') == 'development'

# Layer 2 (Headers): Add security headers
@app.after_request
def add_security_headers(response):
    response.headers['X-Content-Type-Options'] = 'nosniff'
    response.headers['X-Frame-Options'] = 'DENY'
    response.headers['X-XSS-Protection'] = '1; mode=block'
    response.headers['Strict-Transport-Security'] = 'max-age=31536000; includeSubDomains'
    response.headers['Content-Security-Policy'] = "default-src 'self'"
    return response

# Layer 3 (CORS): Restrict origins
# NEVER: CORS(app, origins='*')
# INSTEAD:
CORS(app, origins=['https://app.example.com'], supports_credentials=True)

# Layer 4 (Errors): Custom error handlers (no stack traces)
@app.errorhandler(500)
def internal_error(error):
    logger.error(f'Internal error: {error}')  # Log full error
    return jsonify({'error': 'Internal server error'}), 500  # Generic message"""
        else:
            root_cause = f"Security control missing for {vuln_type}"
            after_code = f"""// TODO: Fix {vuln_type} vulnerability
// Root cause: {root_cause}
// 
// Apply defense-in-depth:
// Layer 1 (Entry): Validate input at API boundary
// Layer 2 (Business): Sanitize before dangerous operation
// Layer 3 (Output): Encode when rendering
// Layer 4 (Detection): Log security events
//
// Hint: {hint}"""
        
        return FixOption(
            option=1,
            description=f"Defense-in-depth fix for {vuln_type}",
            approach=approach,
            code_diff=CodeDiff(
                file=file_path,
                before=vuln_code[:200] if vuln_code else "# Vulnerable code",
                after=after_code,
                lines_changed=len(after_code.split('\n'))
            ),
            test_code=f"""def test_{vuln_type.replace('-', '_')}_fix():
    '''Test that {vuln_type} is properly mitigated'''
    # Test Layer 1: Malicious input is rejected
    # Test Layer 2: Safe API is used correctly  
    # Test Layer 3: Output is properly encoded/validated
    
    # Example: Test SQL injection fix
    # malicious_input = "1; DROP TABLE users;--"
    # result = make_request(malicious_input)
    # assert result.status_code == 400  # Rejected at entry
    
    assert True  # TODO: Implement actual test""",
            safety_gates={},
            confidence=0.7,  # Moderate confidence for template fix
            recommendation="WEAK_ACCEPT",
            reasoning=f"Root cause: {root_cause}. Template-based defense-in-depth fix applied."
        )
    
    def _create_default_fix(self, vuln_data: Dict[str, Any]) -> FixOption:
        """Alias for backward compatibility"""
        return self._create_template_fix(vuln_data)
    
    def format_output(self, result: Dict[str, Any]) -> BLUEAgentOutput:
        """Format BLUE Agent output"""
        return BLUEAgentOutput(
            agent_id=self.agent_id,
            timestamp=datetime.now().isoformat(),
            status="success" if result.get("fixes") else "error",
            fix_id=result["fix_id"],
            vulnerability_id=result["vulnerability_id"],
            fixes=[FixOption(**f) for f in result["fixes"]],
            selected_fix=result["selected_fix"],
            statistics=result["statistics"]
        )
