"""
Ouroboros AI - BLUE Agent
Secure fix generation using DeepSeek-R1-Distill-Qwen-7B with chain-of-thought reasoning
"""

import logging
import json
from typing import Dict, Any, List
from datetime import datetime
from pydantic import BaseModel, Field
from langchain_community.llms import LlamaCpp

from src.agents.base_agent import BaseAgent, AgentInput, AgentOutput
from src.models import get_model
from src.security import safety_gates, GateResult

logger = logging.getLogger(__name__)


class CodeDiff(BaseModel):
    """Code diff for a fix"""
    file: str
    before: str
    after: str
    lines_changed: int


class FixOption(BaseModel):
    """Single fix option generated by BLUE Agent"""
    option: int
    description: str
    approach: str
    code_diff: CodeDiff
    test_code: str
    safety_gates: Dict[str, GateResult]
    confidence: float
    recommendation: str  # STRONG_ACCEPT|ACCEPT|WEAK_ACCEPT|REJECT
    reasoning: str = ""


class BLUEAgentInput(AgentInput):
    """Input schema for BLUE Agent"""
    vulnerability_id: str
    vulnerability_type: str
    vulnerability_location: Dict[str, Any]
    vulnerable_code: str
    cwe: str
    cvss: float
    language: str = Field(default="python")


class BLUEAgentOutput(AgentOutput):
    """Output schema for BLUE Agent"""
    fix_id: str
    vulnerability_id: str
    fixes: List[FixOption]
    selected_fix: int
    statistics: Dict[str, Any]


class BLUEAgent(BaseAgent):
    """
    BLUE Agent - Defensive security specialist
    
    Uses DeepSeek-R1-Distill-Qwen-7B for secure fix generation
    with built-in chain-of-thought reasoning
    """
    
    def __init__(self):
        """Initialize BLUE Agent with DeepSeek-R1 model"""
        model = get_model("blue")
        super().__init__(model=model, agent_id="BLUE")
        
        # System prompt for DeepSeek-R1
        self.system_prompt = """You are DeepSeek-R1, a world-class security engineer specializing in secure code fixes.

REASONING PROTOCOL:
1. Analyze the vulnerability deeply (think step-by-step)
2. Consider multiple fix approaches
3. Evaluate trade-offs (security vs performance vs maintainability)
4. Select the optimal approach with justification

TASK: Fix this vulnerability with SAFE, TESTED, EFFECTIVE code.

OUTPUT (JSON with EXACTLY 3 fix options + reasoning):
{
  "reasoning": {
    "vulnerability_analysis": "Step-by-step analysis of the vulnerability",
    "fix_approaches_considered": ["Approach 1", "Approach 2", "Approach 3"],
    "trade_offs": "Security vs performance vs complexity analysis",
    "selected_approach": "Why this approach is optimal"
  },
  "fixes": [
    {
      "option": 1,
      "description": "Conservative approach (safest)",
      "approach": "parameterized_queries",
      "code_diff": {
        "file": "src/app.py",
        "before": "cursor.execute('SELECT * FROM users WHERE id=' + user_id)",
        "after": "cursor.execute('SELECT * FROM users WHERE id=%s', (user_id,))",
        "lines_changed": 1
      },
      "test_code": "def test_fix(): assert safe_query(1) is not None",
      "confidence": 0.92
    },
    {
      "option": 2,
      "description": "Balanced approach",
      "approach": "orm_migration",
      "code_diff": {...},
      "test_code": "...",
      "confidence": 0.88
    },
    {
      "option": 3,
      "description": "Optimal approach (best performance)",
      "approach": "prepared_statements",
      "code_diff": {...},
      "test_code": "...",
      "confidence": 0.85
    }
  ]
}

5-LAYER SAFETY GATES (ALL must pass):
1. Input Validation: All inputs validated (whitelist, length, type)
2. No New Vulnerabilities: Semgrep scan finds zero new CWEs
3. Backward Compatibility: Existing tests pass 100%
4. Performance: Overhead <10%
5. Test Coverage: New code coverage >80%

DANGEROUS PATTERNS TO AVOID:
❌ subprocess.call(..., shell=True)
❌ eval(), exec(), __import__()
❌ os.system()
❌ String concatenation in SQL queries
❌ Unescaped user input in HTML

REQUIRED PATTERNS:
✅ Parameterized queries (ORM or prepared statements)
✅ Input validation with regex/type checking
✅ HTML escaping (html.escape(), markupsafe)
✅ Use standard crypto libraries (cryptography.io)
✅ Include test code that verifies fix works"""
    
    def validate_input(self, input_data: Dict[str, Any]) -> BLUEAgentInput:
        """Validate BLUE Agent input"""
        return BLUEAgentInput(**input_data)
    
    async def execute(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute BLUE Agent fix generation
        
        Steps:
        1. Analyze vulnerability with DeepSeek-R1
        2. Generate 3 fix options
        3. Validate each fix through 5 safety gates
        4. Select best fix (highest confidence + all gates passed)
        """
        fix_id = f"BLUE-{datetime.now().strftime('%Y%m%d-%H%M%S')}-{input_data['vulnerability_id']}"
        self.logger.info(f"Generating fix {fix_id} for {input_data['vulnerability_type']}")
        
        try:
            # Step 1: Generate fix options with DeepSeek-R1
            self.logger.info("Generating fix options with DeepSeek-R1...")
            fix_options = await self._generate_fixes(input_data)
            
            # Step 2: Validate each fix through safety gates
            self.logger.info("Validating fixes through safety gates...")
            validated_fixes = []
            for fix_option in fix_options:
                validated_fix = await self._validate_fix(fix_option, input_data)
                validated_fixes.append(validated_fix)
            
            # Step 3: Select best fix
            selected_fix_idx = self._select_best_fix(validated_fixes)
            
            self.logger.info(f"Selected fix option {selected_fix_idx + 1}")
            
            # Calculate statistics
            statistics = {
                "total_options": len(validated_fixes),
                "avg_confidence": sum(f.confidence for f in validated_fixes) / len(validated_fixes),
                "all_gates_passed": all(
                    all(g.status.value == "passed" for g in f.safety_gates.values())
                    for f in validated_fixes
                )
            }
            
            return {
                "fix_id": fix_id,
                "vulnerability_id": input_data["vulnerability_id"],
                "fixes": [f.model_dump() for f in validated_fixes],
                "selected_fix": selected_fix_idx + 1,
                "statistics": statistics
            }
            
        except Exception as e:
            self.logger.error(f"BLUE Agent execution failed: {e}", exc_info=True)
            return {
                "fix_id": fix_id,
                "vulnerability_id": input_data["vulnerability_id"],
                "fixes": [],
                "selected_fix": 0,
                "statistics": {"error": str(e)}
            }
    
    async def _generate_fixes(self, vuln_data: Dict[str, Any]) -> List[FixOption]:
        """
        Generate 3 fix options using DeepSeek-R1
        """
        # Construct prompt
        prompt = f"""{self.system_prompt}

VULNERABILITY TO FIX:
Type: {vuln_data['vulnerability_type']}
CWE: {vuln_data['cwe']}
CVSS: {vuln_data['cvss']}
Location: {vuln_data['vulnerability_location']}

VULNERABLE CODE:
```{vuln_data['language']}
{vuln_data['vulnerable_code']}
```

Generate 3 fix options with chain-of-thought reasoning. Output JSON only."""
        
        try:
            # Call DeepSeek-R1
            response = self._call_llm(prompt)
            
            # Parse JSON response
            result = self._parse_json_response(response)
            
            # Extract reasoning (DeepSeek-R1 feature)
            reasoning = result.get("reasoning", {})
            self.logger.info(f"DeepSeek-R1 reasoning: {reasoning.get('selected_approach', 'N/A')}")
            
            # Convert to FixOption objects
            fix_options = []
            for fix_data in result.get("fixes", []):
                try:
                    # Initialize empty safety gates (to be filled later)
                    fix_data["safety_gates"] = {}
                    fix_data["recommendation"] = "PENDING"
                    fix_data["reasoning"] = reasoning.get("selected_approach", "")
                    
                    fix = FixOption(**fix_data)
                    fix_options.append(fix)
                except Exception as e:
                    self.logger.error(f"Failed to parse fix option: {e}")
                    continue
            
            if len(fix_options) < 3:
                self.logger.warning(f"Only generated {len(fix_options)} fix options (expected 3)")
            
            return fix_options
            
        except Exception as e:
            self.logger.error(f"Fix generation failed: {e}")
            # Return a default safe fix
            return [self._create_default_fix(vuln_data)]
    
    async def _validate_fix(self, fix: FixOption, vuln_data: Dict[str, Any]) -> FixOption:
        """
        Validate a fix through 5 safety gates
        """
        self.logger.info(f"Validating fix option {fix.option}")
        
        # Run safety gates
        all_passed, gate_results = await safety_gates.validate_fix(
            original_code=vuln_data["vulnerable_code"],
            fixed_code=fix.code_diff.after,
            test_code=fix.test_code,
            language=vuln_data.get("language", "python")
        )
        
        # Convert gate results to dict
        fix.safety_gates = {
            gate.gate_name: gate
            for gate in gate_results
        }
        
        # Adjust confidence based on gate results
        if not all_passed:
            fix.confidence = min(fix.confidence, 0.5)
            fix.recommendation = "REJECT"
        elif fix.confidence >= 0.9:
            fix.recommendation = "STRONG_ACCEPT"
        elif fix.confidence >= 0.8:
            fix.recommendation = "ACCEPT"
        else:
            fix.recommendation = "WEAK_ACCEPT"
        
        return fix
    
    def _select_best_fix(self, fixes: List[FixOption]) -> int:
        """
        Select the best fix from multiple options
        
        Priority:
        1. All safety gates passed
        2. Highest confidence score
        3. Simplest approach (lowest lines changed)
        """
        # Filter for fixes with all gates passed
        valid_fixes = [
            (i, f) for i, f in enumerate(fixes)
            if all(g.status.value == "passed" for g in f.safety_gates.values())
        ]
        
        if not valid_fixes:
            self.logger.warning("No fixes passed all safety gates, selecting best available")
            valid_fixes = list(enumerate(fixes))
        
        # Sort by confidence (descending)
        valid_fixes.sort(key=lambda x: x[1].confidence, reverse=True)
        
        return valid_fixes[0][0]
    
    def _create_default_fix(self, vuln_data: Dict[str, Any]) -> FixOption:
        """Create a default safe fix if generation fails"""
        return FixOption(
            option=1,
            description="Safe default fix (manual review required)",
            approach="default",
            code_diff=CodeDiff(
                file=vuln_data["vulnerability_location"].get("file", "unknown"),
                before=vuln_data["vulnerable_code"],
                after="# TODO: Manual fix required\npass",
                lines_changed=1
            ),
            test_code="# TODO: Add tests",
            safety_gates={},
            confidence=0.0,
            recommendation="REJECT"
        )
    
    def format_output(self, result: Dict[str, Any]) -> BLUEAgentOutput:
        """Format BLUE Agent output"""
        return BLUEAgentOutput(
            agent_id=self.agent_id,
            timestamp=datetime.now().isoformat(),
            status="success" if result.get("fixes") else "error",
            fix_id=result["fix_id"],
            vulnerability_id=result["vulnerability_id"],
            fixes=[FixOption(**f) for f in result["fixes"]],
            selected_fix=result["selected_fix"],
            statistics=result["statistics"]
        )
