"""
Ouroboros AI - DOCUMENTATION Agent
Creates security reports as PDF from Markdown using Phi-3.5-mini
"""

import logging
import os
from pathlib import Path
from typing import Dict, Any, List
from datetime import datetime
from pydantic import BaseModel, Field

from src.agents.base_agent import BaseAgent, AgentInput, AgentOutput
from src.models import get_model

logger = logging.getLogger(__name__)


class DocumentationAgentInput(AgentInput):
    """Input schema for DOCUMENTATION Agent"""
    vulnerabilities: List[Dict[str, Any]]
    metadata: Dict[str, Any]
    governance_plan: List[Dict[str, Any]] = Field(default_factory=list)
    fixes: List[Dict[str, Any]] = Field(default_factory=list)
    report_type: str = Field(default="initial")  # initial | final


class ReportInfo(BaseModel):
    """Report file information"""
    report_id: str
    pdf_path: str
    md_path: str
    title: str
    created_at: str


class DocumentationAgentOutput(AgentOutput):
    """Output schema for DOCUMENTATION Agent"""
    documentation_id: str
    report_info: ReportInfo
    sections_generated: List[str]
    content_summary: Dict[str, Any]


class DocumentationAgent(BaseAgent):
    """
    DOCUMENTATION Agent - Technical documentation specialist
    
    Uses Phi-3.5-mini-instruct for creating security reports as PDF
    """
    
    # Report output directory
    REPORTS_DIR = Path("outputs/reports")
    
    def __init__(self):
        """Initialize DOCUMENTATION Agent with Phi-3.5 model"""
        model = get_model("documentation")
        super().__init__(model=model, agent_id="DOCUMENTATION")
        
        # Ensure reports directory exists
        self.REPORTS_DIR.mkdir(parents=True, exist_ok=True)
        
        self.system_prompt = """You are Phi-3.5, a technical documentation specialist for security reports.

TASK: Generate a comprehensive, professional security report in MARKDOWN format.

REQUIRED SECTIONS:

# Executive Summary
- Total vulnerabilities found
- Severity breakdown (Critical/High/Medium/Low)
- Overall risk score (0-100)
- Scan duration and scope

# Vulnerability Details

For EACH vulnerability, include:
## [Vulnerability Title] - [Severity]
- **Type**: SQL Injection, XSS, RCE, etc.
- **CWE**: CWE-XX
- **CVSS Score**: X.X
- **Location**: `file:line:function`
- **Description**: Technical explanation
- **Impact**: Business impact and risk

### Proof of Concept
```
[PoC code block]
```

### Recommended Fix
[Fix description]

# Remediation Summary

| ID | Type | Severity | Status | Fix Applied |
|----|------|----------|--------|-------------|
[Table rows for each vulnerability]

# Compliance Mapping
- **SOC2**: [Controls addressed]
- **ISO27001**: [Controls addressed]  
- **GDPR**: Article 32 compliance status
- **PCI-DSS**: [Requirements met]

# Recommendations
1. [Priority recommendations]
2. [Additional hardening]
3. [Monitoring suggestions]

---
*Report generated by Ouroboros AI Security System*
*Timestamp: [ISO timestamp]*

FORMAT RULES:
- Use proper Markdown syntax
- Use code blocks with language hints
- Use tables for structured data
- Be concise but comprehensive
- Include all vulnerability details"""

    def validate_input(self, input_data: Dict[str, Any]) -> DocumentationAgentInput:
        """Validate DOCUMENTATION Agent input"""
        return DocumentationAgentInput(**input_data)
    
    async def execute(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """Execute DOCUMENTATION Agent to create PDF report"""
        doc_id = f"DOC-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        self.logger.info(f"Creating documentation {doc_id}")
        
        try:
            # Generate markdown report content
            md_content = await self._generate_markdown_report(input_data)
            
            # Get report metadata
            repo_name = input_data.get("metadata", {}).get("repo_name", "unknown")
            report_type = input_data.get("report_type", "initial")
            timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
            
            # Create filename
            safe_repo_name = repo_name.replace("/", "_").replace("\\", "_")
            base_filename = f"ouroboros-{report_type}-{safe_repo_name}-{timestamp}"
            
            # Save markdown file
            md_path = self.REPORTS_DIR / f"{base_filename}.md"
            md_path.write_text(md_content, encoding="utf-8")
            self.logger.info(f"Saved markdown report: {md_path}")
            
            # Generate PDF from markdown
            pdf_path = await self._generate_pdf(md_content, base_filename)
            
            # Calculate summary
            vulns = input_data.get("vulnerabilities", [])
            severity_breakdown = self._calculate_severity(vulns)
            
            report_info = {
                "report_id": doc_id,
                "pdf_path": str(pdf_path) if pdf_path else "",
                "md_path": str(md_path),
                "title": f"Ouroboros Security Report - {repo_name}",
                "created_at": datetime.now().isoformat()
            }
            
            sections = [
                "Executive Summary",
                "Vulnerability Details",
                "Remediation Summary",
                "Compliance Mapping",
                "Recommendations"
            ]
            
            if input_data.get("fixes"):
                sections.insert(2, "Fix Details")
            
            return {
                "documentation_id": doc_id,
                "report_info": report_info,
                "doc_url": str(pdf_path) if pdf_path else str(md_path),  # Backward compat
                "doc_id": doc_id,  # Backward compat
                "sections_generated": sections,
                "content_summary": {
                    "total_vulnerabilities": len(vulns),
                    "severity_breakdown": severity_breakdown,
                    "risk_score": self._calculate_risk_score(vulns),
                    "pdf_generated": pdf_path is not None
                }
            }
            
        except Exception as e:
            self.logger.error(f"Documentation creation failed: {e}", exc_info=True)
            return {
                "documentation_id": doc_id,
                "report_info": None,
                "doc_url": "",
                "doc_id": doc_id,
                "sections_generated": [],
                "content_summary": {"error": str(e)}
            }
    
    async def _generate_markdown_report(self, data: Dict[str, Any]) -> str:
        """Generate markdown report content using Phi-3.5"""
        vulns = data.get("vulnerabilities", [])
        fixes = data.get("fixes", [])
        metadata = data.get("metadata", {})
        report_type = data.get("report_type", "initial")
        
        # Build vulnerability summary for prompt
        vuln_summary = self._format_vulnerabilities_for_prompt(vulns)
        fix_summary = self._format_fixes_for_prompt(fixes) if fixes else "No fixes generated yet."
        
        prompt = f"""{self.system_prompt}

REPORT TYPE: {report_type.upper()}

SCAN METADATA:
- Repository: {metadata.get('repo_url', 'N/A')}
- Scan ID: {metadata.get('scan_id', 'N/A')}
- Branch: {metadata.get('branch', 'main')}
- Timestamp: {datetime.now().isoformat()}

VULNERABILITIES FOUND ({len(vulns)} total):
{vuln_summary}

FIX STATUS:
{fix_summary}

Generate a complete Markdown security report. Output ONLY the Markdown content, no extra text."""
        
        try:
            response = self._call_llm(prompt)
            
            # Clean up response - remove markdown code fence if LLM wrapped it
            if response.startswith("```markdown"):
                response = response[len("```markdown"):].strip()
            if response.startswith("```md"):
                response = response[len("```md"):].strip()
            if response.startswith("```"):
                response = response[3:].strip()
            if response.endswith("```"):
                response = response[:-3].strip()
            
            return response
            
        except Exception as e:
            self.logger.error(f"LLM report generation failed: {e}")
            # Return a basic fallback report
            return self._generate_fallback_report(data)
    
    def _format_vulnerabilities_for_prompt(self, vulns: List[Dict]) -> str:
        """Format vulnerabilities for LLM prompt"""
        if not vulns:
            return "No vulnerabilities found."
        
        lines = []
        for i, v in enumerate(vulns, 1):
            loc = v.get("location", {})
            if isinstance(loc, dict):
                loc_str = f"{loc.get('file', 'unknown')}:{loc.get('line', 0)}"
            else:
                loc_str = str(loc)
            
            lines.append(f"""
{i}. {v.get('type', 'Unknown')} ({v.get('severity', 'medium').upper()})
   - CWE: {v.get('cwe', 'N/A')}
   - CVSS: {v.get('cvss', 0.0)}
   - Location: {loc_str}
   - Description: {v.get('description', 'No description')[:200]}
   - PoC: {v.get('poc_code', 'N/A')[:100]}...""")
        
        return "\n".join(lines)
    
    def _format_fixes_for_prompt(self, fixes: List[Dict]) -> str:
        """Format fixes for LLM prompt"""
        if not fixes:
            return "No fixes applied."
        
        lines = []
        for f in fixes:
            lines.append(f"""
- Fix ID: {f.get('fix_id', 'N/A')}
  Vulnerability: {f.get('vulnerability_id', 'N/A')}
  Approach: {f.get('approach', 'N/A')}
  Verified: {f.get('verified', False)}""")
        
        return "\n".join(lines)
    
    def _generate_fallback_report(self, data: Dict[str, Any]) -> str:
        """Generate basic markdown report when LLM fails"""
        vulns = data.get("vulnerabilities", [])
        metadata = data.get("metadata", {})
        timestamp = datetime.now().isoformat()
        
        severity_counts = self._calculate_severity(vulns)
        
        report = f"""# Ouroboros Security Report

**Repository**: {metadata.get('repo_url', 'Unknown')}  
**Scan ID**: {metadata.get('scan_id', 'Unknown')}  
**Generated**: {timestamp}

---

## Executive Summary

| Metric | Value |
|--------|-------|
| Total Vulnerabilities | {len(vulns)} |
| Critical | {severity_counts.get('critical', 0)} |
| High | {severity_counts.get('high', 0)} |
| Medium | {severity_counts.get('medium', 0)} |
| Low | {severity_counts.get('low', 0)} |
| Risk Score | {self._calculate_risk_score(vulns):.1f}/100 |

---

## Vulnerability Details

"""
        for i, v in enumerate(vulns, 1):
            loc = v.get("location", {})
            if isinstance(loc, dict):
                loc_str = f"`{loc.get('file', 'unknown')}:{loc.get('line', 0)}`"
            else:
                loc_str = f"`{loc}`"
            
            report += f"""### {i}. {v.get('type', 'Unknown Vulnerability')}

- **Severity**: {v.get('severity', 'medium').upper()}
- **CWE**: {v.get('cwe', 'N/A')}
- **CVSS**: {v.get('cvss', 0.0)}
- **Location**: {loc_str}
- **Confidence**: {v.get('confidence', 0.0):.0%}

**Description**: {v.get('description', 'No description available.')}

"""
            if v.get('poc_code'):
                report += f"""**Proof of Concept**:
```
{v.get('poc_code', '')}
```

"""
        
        report += f"""---

## Recommendations

1. Address all Critical and High severity vulnerabilities immediately
2. Review code patterns that led to these vulnerabilities
3. Implement security testing in CI/CD pipeline

---

*Report generated by Ouroboros AI Security System*  
*Timestamp: {timestamp}*
"""
        return report
    
    async def _generate_pdf(self, md_content: str, base_filename: str) -> Path:
        """
        Generate PDF from markdown content using WeasyPrint.
        
        Returns the path to the generated PDF, or None if generation fails.
        """
        pdf_path = self.REPORTS_DIR / f"{base_filename}.pdf"
        
        try:
            import markdown
            from weasyprint import HTML
            
            # Convert markdown to HTML
            html_content = markdown.markdown(
                md_content,
                extensions=['tables', 'fenced_code', 'toc']
            )
            
            # Wrap with styled HTML document
            styled_html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Ouroboros Security Report</title>
    <style>
        @page {{
            size: A4;
            margin: 2cm;
            @bottom-center {{
                content: "Page " counter(page) " of " counter(pages);
                font-size: 10px;
                color: #666;
            }}
        }}
        
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            font-size: 11pt;
        }}
        
        h1 {{
            color: #1a1a2e;
            border-bottom: 3px solid #16213e;
            padding-bottom: 10px;
            margin-top: 0;
        }}
        
        h2 {{
            color: #16213e;
            border-bottom: 1px solid #e0e0e0;
            padding-bottom: 5px;
            margin-top: 25px;
        }}
        
        h3 {{
            color: #0f3460;
            margin-top: 20px;
        }}
        
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
            font-size: 10pt;
        }}
        
        th, td {{
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }}
        
        th {{
            background-color: #16213e;
            color: white;
        }}
        
        tr:nth-child(even) {{
            background-color: #f9f9f9;
        }}
        
        code {{
            background-color: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Consolas', 'Monaco', monospace;
            font-size: 10pt;
        }}
        
        pre {{
            background-color: #1a1a2e;
            color: #e0e0e0;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
            font-size: 9pt;
        }}
        
        pre code {{
            background-color: transparent;
            color: inherit;
            padding: 0;
        }}
        
        .critical {{ color: #dc3545; font-weight: bold; }}
        .high {{ color: #fd7e14; font-weight: bold; }}
        .medium {{ color: #ffc107; }}
        .low {{ color: #28a745; }}
        
        blockquote {{
            border-left: 4px solid #16213e;
            margin: 15px 0;
            padding-left: 15px;
            color: #666;
        }}
        
        hr {{
            border: none;
            border-top: 1px solid #e0e0e0;
            margin: 25px 0;
        }}
        
        ul, ol {{
            margin-left: 20px;
        }}
        
        li {{
            margin-bottom: 5px;
        }}
    </style>
</head>
<body>
{html_content}
</body>
</html>"""
            
            # Generate PDF
            HTML(string=styled_html).write_pdf(str(pdf_path))
            
            self.logger.info(f"Generated PDF report: {pdf_path}")
            return pdf_path
            
        except ImportError as e:
            self.logger.warning(f"PDF generation dependencies not available: {e}")
            self.logger.info("Install with: pip install markdown weasyprint")
            return None
            
        except Exception as e:
            self.logger.error(f"PDF generation failed: {e}", exc_info=True)
            return None
    
    def _calculate_severity(self, vulns: List[Dict]) -> Dict[str, int]:
        """Calculate severity breakdown"""
        breakdown = {"critical": 0, "high": 0, "medium": 0, "low": 0}
        for v in vulns:
            sev = v.get("severity", "low").lower()
            if sev in breakdown:
                breakdown[sev] += 1
            else:
                breakdown["low"] += 1
        return breakdown
    
    def _calculate_risk_score(self, vulns: List[Dict]) -> float:
        """Calculate overall risk score (0-100)"""
        if not vulns:
            return 0.0
        
        weights = {"critical": 25, "high": 15, "medium": 7, "low": 2}
        total = sum(weights.get(v.get("severity", "low").lower(), 2) for v in vulns)
        
        # Normalize to 0-100, cap at 100
        return min(100.0, total)
    
    def format_output(self, result: Dict[str, Any]) -> DocumentationAgentOutput:
        """Format DOCUMENTATION Agent output"""
        report_info = result.get("report_info")
        
        return DocumentationAgentOutput(
            agent_id=self.agent_id,
            timestamp=datetime.now().isoformat(),
            status="success" if report_info else "error",
            documentation_id=result["documentation_id"],
            report_info=ReportInfo(**report_info) if report_info else None,
            sections_generated=result.get("sections_generated", []),
            content_summary=result.get("content_summary", {})
        )
